version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./:/var/lib/postgres
      # Windows
      # - C:\workspace\rust\basquet-server\postgres:/var/lib/postgres
      # Linux / Mac
      # - ./postgres:/var/lib/postgres
  
  redis:
    image: redis:latest
  
  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/app_db
    ports:
      - 8000:8000
    volumes:
      - ./:/app